# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS
LAUNCHKEY_DOMAIN: http://pixelmob.co
LAUNCHKEY_APP_ID: 2321526504
LAUNCHKEY_APP_SECRET: a8tyzaq3epv41gey2ac8r2l6ne21e3kk
LAUNCHKEY_KEYPAIR_PASSPHRASE: D9YGpyo322hDhplHUqJMsBuP901bw5L493xh9OwRI4rckY0kHwVU3lfo7pWOIIdxhYUQxEwTIoQjchK5i1xCg