PixelMob.Router.reopen
	location: 'history'

PixelMob.Router.map ->
	@resource "videos",
		path: "/videos"
	@resource "videos",
		path: "/v"
	@resource "video",
		path: "/v/:video_slug/:video_token"
	@resource "edit_video",
		path: "/v/:video_id/e"
	@resource "edit_video",
		path: "/videos/:video_token/:video_slug/edit"
	@resource "new_tag",
		path: "/tags/new"
	@resource "channel",
		path: "/c/:channel_id"
	@resource "channel",
		path: "/channels/:channel_id"
	@resource "upload_container",
		path: "/upload"
	@resource "new_channel",
		path: "/channels/new"
	@resource "tag",
	    path: "/tags/:tag_id"
	@resource "signin",
		path: "/signin"
	@resource "signoff",
		path: "/signoff"
	@resource "subscriptions",
		path: "/subscriptions"
	@resource "subscriptions",
		path: "/"
	@route "video_search",
		path: "/v/s/"
		queryParams: ['search','page']
	@resource "videos",
        path: "/v/p/:page"
	@resource "game",
		path: "/g/:game_id"
	@resource "game",
		path: "/games/:game_id"
	@resource "dashboard",
		path: "/dashboard",
		queryParams: ["channel"]
	@resource "enable_launchkey",
		path: "/enablelaunchkey" 
	@resource "signup",
		path: "/signup"
	@route "pagenotfound",
		path: "*:"